export default loadInstruments = () => {return { 
  "flute1": { 
    name_de: "Flöte", 
    name_en: "Flute",
    practiceSoundPath1: "/einspielen/sounds_flute_einspielen1.mp3",
    practiceSoundPath2: "/einspielen/sounds_flute_einspielen2.mp3",
    sequenceGroup: "flute1",
    image: require('../assets/img/instruments/flute_frame.png'),   
    video: require('../assets/video/instruments/Flute.mov'),
    order: 1,
    priority: 1
  },
  "oboe1": { 
    name_de: "Oboe 1", 
    name_en: "Oboe 1",
    practiceSoundPath1: "/einspielen/sounds_oboe1_einspielen1.mp3",
    practiceSoundPath2: "/einspielen/sounds_oboe1_einspielen2.mp3",
    sequenceGroup: "oboe1",
    image: require('../assets/img/instruments/oboe_frame.png'),    
    video: require('../assets/video/instruments/Oboe.mov'),
    order: 2,
    priority: 1 
  },
  "oboe2": { 
    name_de: "Oboe 2", 
    name_en: "Oboe 2",
    practiceSoundPath1: "/einspielen/sounds_oboe1_einspielen1.mp3",
    practiceSoundPath2: "/einspielen/sounds_oboe1_einspielen2.mp3",
    sequenceGroup: "oboe2",
    image: require('../assets/img/instruments/oboe_frame.png'),
    video: require('../assets/video/instruments/Oboe.mov'),
    order: 3,
    priority: 2
  },
  "fagott1": { 
    name_de: "Fagott 1", 
    name_en: "Bassoon 1",
    sequenceGroup: "fagott1",
    practiceSoundPath1: "/einspielen/sounds_fagott_stimmen.mp3",
    practiceSoundPath2: "/einspielen/sounds_fagott_einspielen1.mp3",
    image: require('../assets/img/instruments/fagott_frame.png'),  
    video: require('../assets/video/instruments/Fagott.mov'),
    order: 4,
    priority: 1 
  },
  "fagott2": { 
    name_de: "Fagott 2", 
    name_en: "Bassoon 2",
    practiceSoundPath1: "/einspielen/sounds_fagott_stimmen.mp3",
    practiceSoundPath2: "/einspielen/sounds_fagott_einspielen1.mp3",
    sequenceGroup: "fagott2",
    image: require('../assets/img/instruments/fagott_frame.png'),  
    video: require('../assets/video/instruments/Fagott.mov'),
    order: 5,
    priority: 2  
  },
  "horn1": { 
    name_de: "Horn 1",
    name_en: "Horn 1",
    practiceSoundPath1: "/einspielen/sounds_horn1_einspielen1.mp3",
    practiceSoundPath2: "/einspielen/sounds_horn1_einspielen2.mp3",
    sequenceGroup: "horn1",
    image: require('../assets/img/instruments/horn_frame.png'),    
    video: require('../assets/video/instruments/Horn.mov'),
    order: 6,
    priority: 1
  },
  "horn2": { 
    name_de: "Horn 2",
    name_en: "Horn 2",
    practiceSoundPath1: "/einspielen/sounds_horn1_einspielen1.mp3",
    practiceSoundPath2: "/einspielen/sounds_horn1_einspielen2.mp3",
    sequenceGroup: "horn2",
    image: require('../assets/img/instruments/horn_frame.png'),
    video: require('../assets/video/instruments/Horn.mov'),
    order: 7,
    priority: 2 
  },
  "trompete1": { 
    name_de: "Trompete 1",
    name_en: "Trumpet 1",
    practiceSoundPath1: "/einspielen/sounds_trumpet_stimmen.mp3",
    practiceSoundPath2: "/einspielen/sounds_trumpet_einspielen.mp3",
    sequenceGroup: "trompete1",
    image: require('../assets/img/instruments/trompete_frame.png'),
    video: require('../assets/video/instruments/Trompete.mov'),
    order: 8,
    priority: 1 
  },
  "trompete2": { 
    name_de: "Trompete 2",
    name_en: "Trumpet 2",
    sequenceGroup: "trompete2",
    practiceSoundPath1: "/einspielen/sounds_trumpet_stimmen.mp3",
    practiceSoundPath2: "/einspielen/sounds_trumpet_einspielen.mp3",
    image: require('../assets/img/instruments/trompete_frame.png'),
    video: require('../assets/video/instruments/Trompete.mov'),
    order: 9,
    priority: 2 
  },
  "pauke1": { 
    name_de: "Pauke",
    name_en: "Timpani",
    practiceSoundPath1: "/einspielen/sounds_pauke1_stimmen.mp3",
    practiceSoundPath2: "/einspielen/sounds_pauke1_einspielen.mp3",
    sequenceGroup: "pauke1",
    image: require('../assets/img/instruments/pauke_frame.png'),
    video: require('../assets/video/instruments/Pauke.mov'),
    order: 10,
    priority: 1
  },
  "piano1":  { 
    name_de: "Klavier", 
    name_en: "Piano",
    practiceSoundPath1: "/einspielen/sounds_piano_einspielen1.mp3",
    practiceSoundPath2: "/einspielen/sounds_piano_einspielen1.mp3",
    sequenceGroup: "piano1",
    image: require('../assets/img/instruments/piano_frame.png'),  
    video: require('../assets/video/instruments/Piano.mov'),
    order: 11,
    priority: 1 
  },
  "violin1.1": { 
    name_de: "Violine 1",
    name_en: "Violin 1",
    practiceSoundPath1: "/einspielen/sounds_violin_stimmen.mp3",
    practiceSoundPath2: "/einspielen/sounds_violin_einspielen.mp3",
    sequenceGroup: "violin1",
    image: require('../assets/img/instruments/violine_frame.png'), 
    video: require('../assets/video/instruments/Violine.mov'),
    order: 12,
    priority: 1
  },
  "violin1.2": { 
    name_de: "Violine 1",
    name_en: "Violin 1",
    sequenceGroup: "violin1",
    practiceSoundPath1: "/einspielen/sounds_violin_stimmen.mp3",
    practiceSoundPath2: "/einspielen/sounds_violin_einspielen.mp3",
    image: require('../assets/img/instruments/violine_frame.png'), 
    video: require('../assets/video/instruments/Violine.mov'),
    order: 13,
    priority: 1
  },
  "violin1.3": { 
    name_de: "Violine 1",
    name_en: "Violin 1",
    sequenceGroup: "violin1",
    practiceSoundPath1: "/einspielen/sounds_violin_stimmen.mp3",
    practiceSoundPath2: "/einspielen/sounds_violin_einspielen.mp3",
    image: require('../assets/img/instruments/violine_frame.png'), 
    video: require('../assets/video/instruments/Violine.mov'),
    order: 14,
    priority: 1
  },
  "violin1.4": { 
    name_de: "Violine 1",
    name_en: "Violin 1",
    sequenceGroup: "violin1",
    practiceSoundPath1: "/einspielen/sounds_violin_stimmen.mp3",
    practiceSoundPath2: "/einspielen/sounds_violin_einspielen.mp3",
    image: require('../assets/img/instruments/violine_frame.png'), 
    video: require('../assets/video/instruments/Violine.mov'),
    order: 15,
    priority: 1
  },
  "violin2.1": { 
    name_de: "Violine 2",
    name_en: "Violin 2",
    sequenceGroup: "violin2",
    practiceSoundPath1: "/einspielen/sounds_violin_stimmen.mp3",
    practiceSoundPath2: "/einspielen/sounds_violin_einspielen.mp3",
    image: require('../assets/img/instruments/violine_frame.png'), 
    video: require('../assets/video/instruments/Violine.mov'),
    order: 16,
    priority: 2
  },
  "violin2.2": { 
    name_de: "Violine 2",
    name_en: "Violin 2",
    practiceSoundPath1: "/einspielen/sounds_violin_stimmen.mp3",
    practiceSoundPath2: "/einspielen/sounds_violin_einspielen.mp3",
    sequenceGroup: "violin2",
    image: require('../assets/img/instruments/violine_frame.png'), 
    video: require('../assets/video/instruments/Violine.mov'),
    order: 17,
    priority: 2
  },
  "violin2.3": { 
    name_de: "Violine 2",
    name_en: "Violin 2",
    practiceSoundPath1: "/einspielen/sounds_violin_stimmen.mp3",
    practiceSoundPath2: "/einspielen/sounds_violin_einspielen.mp3",
    sequenceGroup: "violin2",
    image: require('../assets/img/instruments/violine_frame.png'), 
    video: require('../assets/video/instruments/Violine.mov'),
    order: 18,
    priority: 2
  },
  "violin2.4": { 
    name_de: "Violine 2",
    name_en: "Violin 2",
    practiceSoundPath1: "/einspielen/sounds_violin_stimmen.mp3",
    practiceSoundPath2: "/einspielen/sounds_violin_einspielen.mp3",
    sequenceGroup: "violin2",
    image: require('../assets/img/instruments/violine_frame.png'), 
    video: require('../assets/video/instruments/Violine.mov'),
    order: 19,
    priority: 1
  },
  "viola1.1": { 
    name_de: "Viola",
    name_en: "Viola",
    sequenceGroup: "viola1",
    practiceSoundPath1: "/einspielen/sounds_viola_stimmen.mp3",
    practiceSoundPath2: "/einspielen/sounds_viola_einspielen.mp3",
    image: require('../assets/img/instruments/viola_frame.png'),   
    video: require('../assets/video/instruments/Viola.mov'),
    order: 20,
    priority: 1 
  },
  "viola1.2": { 
    name_de: "Viola",
    name_en: "Viola",
    sequenceGroup: "viola1",
    practiceSoundPath1: "/einspielen/sounds_viola_stimmen.mp3",
    practiceSoundPath2: "/einspielen/sounds_viola_einspielen.mp3",
    image: require('../assets/img/instruments/viola_frame.png'),   
    video: require('../assets/video/instruments/Viola.mov'),
    order: 21,
    priority: 1 
  },
  "viola1.3": { 
    name_de: "Viola",
    name_en: "Viola",
    sequenceGroup: "viola1",
    practiceSoundPath1: "/einspielen/sounds_viola_stimmen.mp3",
    practiceSoundPath2: "/einspielen/einssounds_viola_einspielen.mp3",
    image: require('../assets/img/instruments/viola_frame.png'),   
    video: require('../assets/video/instruments/Viola.mov'),
    order: 22,
    priority: 1 
  },
  "cello1.1": { 
    name_de: "Cello",
    name_en: "Cello",
    practiceSoundPath1: "/einspielen/sounds_cello1.1_stimmen.mp3",
    practiceSoundPath2: "/einspielen/sounds_cello1.1_einspielen.mp3",
    sequenceGroup: "cello",
    image: require('../assets/img/instruments/cello_frame.png'),   
    video: require('../assets/video/instruments/Cello.mov'),
    order: 23,
    priority: 1 
  },
  "cello1.2": { 
    name_de: "Cello",
    name_en: "Cello",
    practiceSoundPath1: "/einspielen/sounds_cello1.1_stimmen.mp3",
    practiceSoundPath2: "/einspielen/sounds_cello1.1_einspielen.mp3",
    sequenceGroup: "cello",
    image: require('../assets/img/instruments/cello_frame.png'),   
    video: require('../assets/video/instruments/Cello.mov'),
    order: 24,
    priority: 1 
  },
  "cello1.3": { 
    name_de: "Cello",
    name_en: "Cello",
    practiceSoundPath1: "/einspielen/sounds_cello1.1_stimmen.mp3",
    practiceSoundPath2: "/einspielen/sounds_cello1.1_einspielen.mp3",
    sequenceGroup: "cello",
    image: require('../assets/img/instruments/cello_frame.png'),
    video: require('../assets/video/instruments/Cello.mov'),
    order: 25,
    priority: 1 
  },
  "bass1.1": { 
    name_de: "Kontrabass",
    name_en: "Double Bass",
    practiceSoundPath1: "/einspielen/bass1.1_stimmen.mp3",
    practiceSoundPath2: "/einspielen/bass1.1_einspielen.mp3",
    sequenceGroup: "bass",
    image: require('../assets/img/instruments/bass_frame.png'),   
    video: require('../assets/video/instruments/Kontrabass.mov'),
    order: 26,
    priority: 1 
  },
  "bass1.2": { 
    name_de: "Kontrabass",
    name_en: "Double Bass",
    practiceSoundPath1: "/einspielen/bass1.1_stimmen.mp3",
    practiceSoundPath2: "/einspielen/bass1.1_einspielen.mp3",    
    sequenceGroup: "bass",
    image: require('../assets/img/instruments/bass_frame.png'),   
    video: require('../assets/video/instruments/Kontrabass.mov'),
    order: 27,
    priority: 1 
  },
}}
