export default loadNavigationAssets = () => {return { 
  "piano1":       { image: require('../assets/img/instruments/Piano.png'),  video: require('../assets/video/instruments/Piano.mov') },
  "flute1":       { image: require('../assets/img/instruments/Flute.png'),   video: require('../assets/video/instruments/Flute.mov') },
  "oboe1":      { image: require('../assets/img/instruments/Oboe.png'),    video: require('../assets/video/instruments/Oboe.mov') },
  "oboe2":      { image: require('../assets/img/instruments/Oboe.png'),    video: require('../assets/video/instruments/Oboe.mov') },
  "fagott1":   { image: require('../assets/img/instruments/Fagott.png'),  video: require('../assets/video/instruments/Fagott.mov') },
  "fagott2":   { image: require('../assets/img/instruments/Fagott.png'),  video: require('../assets/video/instruments/Fagott.mov') },
  "horn1":      { image: require('../assets/img/instruments/Horn.png'),    video: require('../assets/video/instruments/Horn.mov') },
  "horn2":      { image: require('../assets/img/instruments/Horn.png'),    video: require('../assets/video/instruments/Horn.mov') },
  "trompete1":   { image: require('../assets/img/instruments/Trompete.png'),video: require('../assets/video/instruments/Trompete.mov') },
  "trompete2":   { image: require('../assets/img/instruments/Trompete.png'),video: require('../assets/video/instruments/Trompete.mov') },
  "pauke1":     { image: require('../assets/img/instruments/Pauke.png'),   video: require('../assets/video/instruments/Pauke.mov') },
  "violin1":    { image: require('../assets/img/instruments/Violine.png'), video: require('../assets/video/instruments/Violine.mov') },
  "violin1.1":    { image: require('../assets/img/instruments/Violine.png'), video: require('../assets/video/instruments/Violine.mov') },
  "violin1.2":    { image: require('../assets/img/instruments/Violine.png'), video: require('../assets/video/instruments/Violine.mov') },
  "violin1.3":    { image: require('../assets/img/instruments/Violine.png'), video: require('../assets/video/instruments/Violine.mov') },
  "violin1.4":    { image: require('../assets/img/instruments/Violine.png'), video: require('../assets/video/instruments/Violine.mov') },
  "violin2":    { image: require('../assets/img/instruments/Violine.png'), video: require('../assets/video/instruments/Violine.mov') },
  "violin2.1":    { image: require('../assets/img/instruments/Violine.png'), video: require('../assets/video/instruments/Violine.mov') },
  "violin2.2":    { image: require('../assets/img/instruments/Violine.png'), video: require('../assets/video/instruments/Violine.mov') },    
  "violin2.3":    { image: require('../assets/img/instruments/Violine.png'), video: require('../assets/video/instruments/Violine.mov') },    
  "violin2.4":    { image: require('../assets/img/instruments/Violine.png'), video: require('../assets/video/instruments/Violine.mov') },    
  "viola1":       { 
    practiceSoundPath1: "/sounds_viola_stimmen.mp3",
    practiceSoundPath2: "/sounds_viola_einspielen.mp3",
    image: require('../assets/img/instruments/Viola.png'),   video: require('../assets/video/instruments/Viola.mov') },
  "viola1.1":       { 
    practiceSoundPath1: "/sounds_viola_stimmen.mp3",
    practiceSoundPath2: "/sounds_viola_einspielen.mp3",
    image: require('../assets/img/instruments/Viola.png'),   video: require('../assets/video/instruments/Viola.mov') },
"viola1.2":       { 
    practiceSoundPath1: "/sounds_viola_stimmen.mp3",
    practiceSoundPath2: "/sounds_viola_einspielen.mp3",
    image: require('../assets/img/instruments/Viola.png'),   video: require('../assets/video/instruments/Viola.mov') },
"viola1.3":       { 
    practiceSoundPath1: "/sounds_viola_stimmen.mp3",
    practiceSoundPath2: "/sounds_viola_einspielen.mp3",
    image: require('../assets/img/instruments/Viola.png'),   video: require('../assets/video/instruments/Viola.mov') },
  "cello1":       { image: require('../assets/img/instruments/Cello.png'),   video: require('../assets/video/instruments/Cello.mov') },
  "cello1.1":       { image: require('../assets/img/instruments/Cello.png'),   video: require('../assets/video/instruments/Cello.mov') },
  "cello1.2":       { image: require('../assets/img/instruments/Cello.png'),   video: require('../assets/video/instruments/Cello.mov') },
  "cello1.3":       { image: require('../assets/img/instruments/Cello.png'),   video: require('../assets/video/instruments/Cello.mov') },
  "bass1":        { image: require('../assets/img/instruments/Cello.png'),   video: require('../assets/video/instruments/Kontrabass.mov') },
"bass1.1":        { image: require('../assets/img/instruments/Cello.png'),   video: require('../assets/video/instruments/Kontrabass.mov') },
"bass1.2":        { image: require('../assets/img/instruments/Cello.png'),   video: require('../assets/video/instruments/Kontrabass.mov') },
}}
